import { Annotation } from "@langchain/langgraph";
import type {
  RunJobEnvelope,
  WaitMutationAckResponse,
} from "@tooldi/agent-contracts";
type TopologyCompletionContract = {
  topologyId: string;
  requiredCapabilityIds: string[];
  minimumEditableTextCapabilityCount: number;
  requiresActionCapability: boolean;
  requiresMediaCapability: boolean;
};
import type {
  AdaptiveCompositionDecision,
  FinalizeRunDraft,
  AbstractLayoutPlan,
  AbstractLayoutPlanNormalizationReport,
  AssetPlan,
  CompositionBrief,
  CompositionRanking,
  CompositionVariantSet,
  ConcreteLayoutPlan,
  CopyPlan,
  CopyPlanNormalizationReport,
  CopyAtomPlan,
  ExecutionSceneSummary,
  FreeformLayoutPlan,
  HydratedPlanningInput,
  IntentNormalizationReport,
  JudgePlan,
  MutationProposalDraft as WorkerMutationProposalDraft,
  CanonicalDesignBrief,
  SemanticBriefDraftArtifact,
  SceneLayoutPlan,
  SceneRolePlan,
  SceneStylePlan,
  SceneBindingPlan,
  ProcessRunJobResult,
  RefineDecision,
  ReferenceBlockGraph,
  RetrievalStageResult,
  RuleJudgeVerdict,
  SearchProfileArtifact,
  SelectionDecision,
  SkeletonMutationBatch,
  SourceSearchSummary,
  StageAckRecord,
  StyleDowngradeVerdict,
  TemplateCandidateBundle,
  TemplatePriorBundle,
  TemplateSelectionPolicy,
  ReferenceCompositionGraph,
  ReferenceSupportEvidence,
  CopyBindingPlan,
  EditableBlockPlan,
  MessageAtomPlan,
  ObjectNativeCandidateSelection,
  ObjectNativeReferenceAudit,
  ObjectNativeRenderabilityReport,
  ProjectedObjectGraph,
  QualityEvalSummary,
  TopologyBindingPlan,
  TopologyCompletionReport,
  TopologyExecutionPlan,
  TopologyMatchReport,
  TopologySelection,
  TemplateRemixPlan,
  TypographyDecision,
} from "../types.js";
import type {
  TemplatePriorSummary,
} from "@tooldi/agent-contracts";
import type {
  TemplatePlannerMode,
} from "@tooldi/agent-llm";

type SourceSearchBackground = SourceSearchSummary["background"];
type SourceSearchGraphic = SourceSearchSummary["graphic"];
type SourceSearchPhoto = SourceSearchSummary["photo"];
type SourceSearchFont = SourceSearchSummary["font"];

const replaceValue = <T>(defaultFactory: () => T) =>
  Annotation<T>({
    reducer: (_left, right) => right,
    default: defaultFactory,
  });

export const RunJobGraphState = Annotation.Root({
  job: Annotation<RunJobEnvelope>(),
  cooperativeStopRequested: replaceValue(() => false),
  hydrated: replaceValue<HydratedPlanningInput | null>(() => null),
  resolvedPlannerMode: replaceValue<TemplatePlannerMode>(() => "heuristic"),
  semanticBriefDraft: replaceValue<SemanticBriefDraftArtifact | null>(() => null),
  semanticBriefDraftRef: replaceValue<string | null>(() => null),
  intentNormalizationReport: replaceValue<IntentNormalizationReport | null>(() => null),
  briefCompilationReportRef: replaceValue<string | null>(() => null),
  intent: replaceValue<CanonicalDesignBrief | null>(() => null),
  canonicalDesignBriefRef: replaceValue<string | null>(() => null),
  templatePriorBundle: replaceValue<TemplatePriorBundle | null>(() => null),
  templatePriorBundleRef: replaceValue<string | null>(() => null),
  sceneRolePlan: replaceValue<SceneRolePlan | null>(() => null),
  sceneRolePlanRef: replaceValue<string | null>(() => null),
  sceneLayoutPlan: replaceValue<SceneLayoutPlan | null>(() => null),
  sceneLayoutPlanRef: replaceValue<string | null>(() => null),
  sceneStylePlan: replaceValue<SceneStylePlan | null>(() => null),
  sceneStylePlanRef: replaceValue<string | null>(() => null),
  sceneBindingPlan: replaceValue<SceneBindingPlan | null>(() => null),
  sceneBindingPlanRef: replaceValue<string | null>(() => null),
  referenceCompositionGraph: replaceValue<ReferenceCompositionGraph | null>(() => null),
  referenceCompositionGraphRef: replaceValue<string | null>(() => null),
  referenceSupportEvidence: replaceValue<ReferenceSupportEvidence | null>(() => null),
  referenceSupportEvidenceRef: replaceValue<string | null>(() => null),
  copyAtomPlan: replaceValue<CopyAtomPlan | null>(() => null),
  copyAtomPlanRef: replaceValue<string | null>(() => null),
  copyBindingPlan: replaceValue<CopyBindingPlan | null>(() => null),
  copyBindingPlanRef: replaceValue<string | null>(() => null),
  templateRemixPlan: replaceValue<TemplateRemixPlan | null>(() => null),
  templateRemixPlanRef: replaceValue<string | null>(() => null),
  freeformLayoutPlan: replaceValue<FreeformLayoutPlan | null>(() => null),
  freeformLayoutPlanRef: replaceValue<string | null>(() => null),
  styleDowngradeVerdict: replaceValue<StyleDowngradeVerdict | null>(() => null),
  styleDowngradeVerdictRef: replaceValue<string | null>(() => null),
  referenceBlockGraph: replaceValue<ReferenceBlockGraph | null>(() => null),
  referenceBlockGraphRef: replaceValue<string | null>(() => null),
  messageAtomPlan: replaceValue<MessageAtomPlan | null>(() => null),
  messageAtomPlanRef: replaceValue<string | null>(() => null),
  editableBlockPlan: replaceValue<EditableBlockPlan | null>(() => null),
  editableBlockPlanRef: replaceValue<string | null>(() => null),
  qualityEvalSummary: replaceValue<QualityEvalSummary | null>(() => null),
  qualityEvalSummaryRef: replaceValue<string | null>(() => null),
  objectNativeReferenceAudit: replaceValue<ObjectNativeReferenceAudit | null>(() => null),
  objectNativeReferenceAuditRef: replaceValue<string | null>(() => null),
  objectNativeCandidateSelection: replaceValue<ObjectNativeCandidateSelection | null>(() => null),
  objectNativeCandidateSelectionRef: replaceValue<string | null>(() => null),
  objectNativeRenderabilityReport: replaceValue<ObjectNativeRenderabilityReport | null>(() => null),
  objectNativeRenderabilityReportRef: replaceValue<string | null>(() => null),
  projectedTemplateGraph: replaceValue<ProjectedObjectGraph | null>(() => null),
  projectedTemplateGraphRef: replaceValue<string | null>(() => null),
  adaptiveCompositionDecision: replaceValue<AdaptiveCompositionDecision | null>(() => null),
  adaptiveCompositionDecisionRef: replaceValue<string | null>(() => null),
  adaptiveSkeletonBatch: replaceValue<import("../types.js").SkeletonMutationBatch | null>(() => null),
  topologyMatchReport: replaceValue<TopologyMatchReport | null>(() => null),
  topologyMatchReportRef: replaceValue<string | null>(() => null),
  topologySelection: replaceValue<TopologySelection | null>(() => null),
  topologySelectionRef: replaceValue<string | null>(() => null),
  selectedTopologyId: replaceValue<string | null>(() => null),
  topologyCompletionContract: replaceValue<TopologyCompletionContract | null>(() => null),
  topologyBindingPlan: replaceValue<TopologyBindingPlan | null>(() => null),
  topologyBindingPlanRef: replaceValue<string | null>(() => null),
  topologyExecutionPlan: replaceValue<TopologyExecutionPlan | null>(() => null),
  topologyExecutionPlanRef: replaceValue<string | null>(() => null),
  topologyCompletionReport: replaceValue<TopologyCompletionReport | null>(() => null),
  topologyCompletionReportRef: replaceValue<string | null>(() => null),
  compositionBrief: replaceValue<CompositionBrief | null>(() => null),
  compositionBriefRef: replaceValue<string | null>(() => null),
  compositionVariantSet: replaceValue<CompositionVariantSet | null>(() => null),
  compositionVariantSetRef: replaceValue<string | null>(() => null),
  compositionRanking: replaceValue<CompositionRanking | null>(() => null),
  compositionRankingRef: replaceValue<string | null>(() => null),
  copyPlan: replaceValue<CopyPlan | null>(() => null),
  copyPlanRef: replaceValue<string | null>(() => null),
  copyPlanNormalizationReport: replaceValue<CopyPlanNormalizationReport | null>(() => null),
  copyPlanNormalizationReportRef: replaceValue<string | null>(() => null),
  abstractLayoutPlan: replaceValue<AbstractLayoutPlan | null>(() => null),
  abstractLayoutPlanRef: replaceValue<string | null>(() => null),
  abstractLayoutPlanNormalizationReport: replaceValue<AbstractLayoutPlanNormalizationReport | null>(() => null),
  abstractLayoutPlanNormalizationReportRef: replaceValue<string | null>(() => null),
  assetPlan: replaceValue<AssetPlan | null>(() => null),
  assetPlanRef: replaceValue<string | null>(() => null),
  templatePriorSummary: replaceValue<TemplatePriorSummary | null>(() => null),
  templatePriorSummaryRef: replaceValue<string | null>(() => null),
  searchProfile: replaceValue<SearchProfileArtifact | null>(() => null),
  searchProfileRef: replaceValue<string | null>(() => null),
  retrievalStage: replaceValue<RetrievalStageResult | null>(() => null),
  retrievalStageRef: replaceValue<string | null>(() => null),
  selectionPolicy: replaceValue<TemplateSelectionPolicy | null>(() => null),
  candidateSets: replaceValue<TemplateCandidateBundle | null>(() => null),
  candidateSetRef: replaceValue<string | null>(() => null),
  sourceSearchBackground: replaceValue<SourceSearchBackground | null>(() => null),
  sourceSearchGraphic: replaceValue<SourceSearchGraphic | null>(() => null),
  sourceSearchPhoto: replaceValue<SourceSearchPhoto | null>(() => null),
  selectionDecision: replaceValue<SelectionDecision | null>(() => null),
  selectionDecisionRef: replaceValue<string | null>(() => null),
  concreteLayoutPlan: replaceValue<ConcreteLayoutPlan | null>(() => null),
  concreteLayoutPlanRef: replaceValue<string | null>(() => null),
  typographyDecision: replaceValue<TypographyDecision | null>(() => null),
  typographyDecisionRef: replaceValue<string | null>(() => null),
  typographySearchSummary: replaceValue<SourceSearchFont | null>(() => null),
  sourceSearchSummary: replaceValue<SourceSearchSummary | null>(() => null),
  sourceSearchSummaryRef: replaceValue<string | null>(() => null),
  plan: replaceValue<ProcessRunJobResult["plan"] | null>(() => null),
  executablePlanRef: replaceValue<string | null>(() => null),
  ruleJudgeVerdict: replaceValue<RuleJudgeVerdict | null>(() => null),
  ruleJudgeVerdictRef: replaceValue<string | null>(() => null),
  executionSceneSummary: replaceValue<ExecutionSceneSummary | null>(() => null),
  executionSceneSummaryRef: replaceValue<string | null>(() => null),
  judgePlan: replaceValue<JudgePlan | null>(() => null),
  judgePlanRef: replaceValue<string | null>(() => null),
  refineDecision: replaceValue<RefineDecision | null>(() => null),
  refineDecisionRef: replaceValue<string | null>(() => null),
  skeletonBatch: replaceValue<SkeletonMutationBatch | null>(() => null),
  currentStageIndex: replaceValue(() => 0),
  currentProposal: replaceValue<WorkerMutationProposalDraft | null>(() => null),
  currentMutationId: replaceValue<string | null>(() => null),
  emittedMutationIds: replaceValue<string[]>(() => []),
  assignedSeqs: replaceValue<number[]>(() => []),
  lastMutationAck: replaceValue<WaitMutationAckResponse | null>(() => null),
  stageAckHistory: replaceValue<StageAckRecord[]>(() => []),
  refineAttempt: replaceValue<0 | 1>(() => 0),
  finalizeDraft: replaceValue<FinalizeRunDraft | null>(() => null),
  result: replaceValue<ProcessRunJobResult | null>(() => null),
});

export type RunJobGraphStateType = typeof RunJobGraphState.State;
